# Generated by Django 5.2.8 on 2025-11-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_sport_match_sport_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='teams', to='league.sport'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teams', to='league.sport'),
        ),
    ]
